In [ ]:
import numpy as np
a = np.arange(2,49,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [ ]:
b = np.array([1,34,2,32,3,45,4,56,5,67,6,78,7,89,8,90])
c = np.arange(b[0], b[1], b[2])
print(c)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd  # Required import

# 1D container called a Series
data = [2, 3, 4, 5, 6, 11, 12, 13, 14, 15]  # Fixed variable name (no numbers at start)
series = pd.Series(data)

print(series)
print(type(series))
print(series[0])  # Accessing the first element of the Series

0     2
1     3
2     4
3     5
4     6
5    11
6    12
7    13
8    14
9    15
dtype: int64
<class 'pandas.core.series.Series'>
2

In [ ]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [ ]:
print(a.ndim)
print(a.shape)
print(a[3])

1
(24,)
8

### Dictionary

In [ ]:

mydict = {'Name': ['Rajoo', 'Raju', 'Raja', 'Raj'], 'Age': [23, 24, 25, 26], 'City': ['Delhi', 'Mumbai', 'Chennai', 'Kolkata'], 'b': [1, 34, 2], 'c': np.arange(1, 34, 2),2: np.arange(1, 34, 2),6: [1, 34, ]}
ser1 = pd.Series(mydict)
ser1

Name                             [Rajoo, Raju, Raja, Raj]
Age                                      [23, 24, 25, 26]
City                    [Delhi, Mumbai, Chennai, Kolkata]
b                                              [1, 34, 2]
c       [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25...
2       [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25...
6                                                 [1, 34]
dtype: object

In [ ]:
print(ser1['Name'])

['Rajoo', 'Raju', 'Raja', 'Raj']

In [ ]:
print(ser1['City'])

['Delhi', 'Mumbai', 'Chennai', 'Kolkata']

In [ ]:
print(ser1[2])

['Delhi', 'Mumbai', 'Chennai', 'Kolkata']

C:\Users\Rajoo\AppData\Local\Temp\ipykernel_16804\3602713501.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ser1[2])

### Slice

In [ ]:
print(ser1[1:5])

Age                      [23, 24, 25, 26]
City    [Delhi, Mumbai, Chennai, Kolkata]
dtype: object

In [ ]:
print(ser1[0:2])

Name    [Rajoo, Raju, Raja, Raj]
Age             [23, 24, 25, 26]
dtype: object

In [ ]:
print(ser1['Name':'City'])

Name             [Rajoo, Raju, Raja, Raj]
Age                      [23, 24, 25, 26]
City    [Delhi, Mumbai, Chennai, Kolkata]
dtype: object

In [ ]:
d = pd.Series(np.arange(1, 10))
print(d)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

### DataFrame -----> 2d dim container

In [ ]:
a = [["Raju",24,"Delhi"],["Lavanya",25,"Mumbai"],["Rahul",26,"Chennai"]]
b = pd.DataFrame(a,columns=['Name','Age','City'])
b

      Name  Age     City
0     Raju   24    Delhi
1  Lavanya   25   Mumbai
2    Rahul   26  Chennai

In [ ]:
dict1 = {'PID': [1, 2, 3, 4, 5], 'Name': ['Pepsi', 'Coke', 'Sprite', 'Fanta', 'Mountain Dew'], 'quantity': [100, 200, 150, 120, 180], 'Price': [200, 150, 180, 170, 160]}

In [ ]:
df = pd.DataFrame(dict1)
df

   PID          Name  quantity  Price
0    1         Pepsi       100    200
1    2          Coke       200    150
2    3        Sprite       150    180
3    4         Fanta       120    170
4    5  Mountain Dew       180    160

In [ ]:
pwd

'c:\\Users\\Rajoo\\OneDrive\\Desktop\\Data_Scientist_Python'

In [ ]:
import pandas as pd
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df['Pclass'].unique()

array([3, 1, 2])

In [ ]:
df.shape

(891, 12)